/* ============================================================
   Tool data — Jacob Digital AI Buddy.
   Curated tools across categories, with tier (Essentials / Advanced).
   Detailed tools have Peter's full take; lightweight tools have a one-liner.
   ============================================================ */

const TOOL_CATEGORIES = [
  { id: 'all',     label: 'Alle' },
  { id: 'chat',    label: 'Chat / Assistenz' },
  { id: 'media',   label: 'Bild & Audio' },
  { id: 'video',   label: 'Video' },
  { id: 'work',    label: 'Präsentation & Doku' },
  { id: 'build',   label: 'Code & Automation' },
  { id: 'data',    label: 'Daten & Backend' },
  { id: 'work-os', label: 'Productivity' },
  { id: 'design',  label: 'Design' },
  { id: 'reach',   label: 'Marketing' },
];

const TIERS = {
  essential: { id: 'essential', label: 'Essential', short: 'E' },
  advanced:  { id: 'advanced',  label: 'Advanced',  short: 'A' },
};

/* ---------- Detailed tools (with Peter's full take) ---------- */
const DETAILED = [
  {
    id: 'claude', name: 'Claude', maker: 'Anthropic',
    logoBg: '#D97757', logoMark: 'C',
    category: 'chat', tier: 'essential',
    tags: ['Chat', 'Reasoning', 'Analyse'],
    url: 'anthropic.com',
    oneLine: 'Der nüchterne Analyst — stark bei langen Texten, Verträgen, strukturiertem Denken.',
    body: 'Claude ist mein erster Griff, wenn ich eine komplexe Fragestellung durchdenken muss oder einen langen Text strukturiert analysieren will. Antworten sind ruhig, auf den Punkt und ehrlich — er sagt auch mal "das weiß ich nicht".',
    example: 'Vertrag hochladen → kritische Klauseln markieren lassen. 90-seitiges PDF → strukturierte Zusammenfassung in 30 Sekunden.',
    strengths: [
      'Lange Dokumente (200k+ Zeichen) in einem Rutsch',
      'Genaue, prüfbare Textarbeit ohne Halluzinationen im Stil',
      'Starkes Arbeiten mit Tabellen, Code, juristischen Texten',
      'Artefakte: baut kleine Apps & Visualisierungen direkt im Chat',
    ],
    weak: ['Keine echte Bild-Generierung', 'Kein eigenes Web-Browsing in der Basis-Version'],
    useFor: 'Wenn Sie präzise, nachvollziehbare Analyse brauchen — Verträge, Angebote, Spezifikationen, Auswertungen.',
    pricing: 'Free / 20 € mtl.',
    access: 'claude.ai',
  },
  {
    id: 'chatgpt', name: 'ChatGPT', maker: 'OpenAI',
    logoBg: '#10A37F', logoMark: 'G',
    category: 'chat', tier: 'essential',
    tags: ['Chat', 'Bild', 'Voice'],
    url: 'openai.com',
    oneLine: 'Das Schweizer Taschenmesser — kann fast alles, am breitesten aufgestellt.',
    body: 'ChatGPT ist die bekannteste Wahl und hat das breiteste Funktionsspektrum: Text, Bilder generieren, Dateien analysieren, Sprach-Chat. Wenn Sie nur ein Abo haben wollen, das fast alles abdeckt — das hier.',
    example: 'Excel hochladen, Pivot generieren lassen, Bild-Entwurf daneben, alles in einer Session.',
    strengths: [
      'Größtes Ökosystem an Integrationen und GPTs',
      'Native Bildgenerierung direkt integriert',
      'Sehr gutes Voice-Mode für Dialog',
      'Starke Dateianalyse (Excel, PDF, Bilder)',
    ],
    weak: ['Bei sehr langen Texten präziser als Claude? Nein.', 'Tendiert stärker zu ausführlich-fleißigen Antworten'],
    useFor: 'Der Allrounder im Büro. Wenn Sie noch nichts haben und nur ein Tool anschaffen wollen — das hier.',
    pricing: 'Free / 23 € mtl.',
    access: 'chatgpt.com',
  },
  {
    id: 'gemini', name: 'Gemini', maker: 'Google',
    logoBg: '#4285F4', logoMark: 'G',
    category: 'chat', tier: 'essential',
    tags: ['Chat', 'Workspace', 'Multimodal'],
    url: 'gemini.google.com',
    oneLine: 'Der Google-Native — stark, wenn Sie Workspace (Gmail, Docs, Drive) bereits nutzen.',
    body: 'Gemini sitzt direkt in Ihrem Gmail, Docs, Sheets, Drive. Wenn Google Workspace Ihr Arbeitsumfeld ist, holen Sie aus Gemini mehr heraus als aus den anderen — weil er Ihre E-Mails und Ordner kennt.',
    example: 'Gmail: "Fass mir die Gespräche mit Kunde X der letzten 4 Wochen zusammen." Drive: "Erstelle aus diesen drei Docs ein Angebot."',
    strengths: [
      'Tiefe Workspace-Integration (Gmail, Docs, Sheets, Drive)',
      'Sehr großes Kontextfenster (1 Mio+ Token)',
      'Stärkste Multimodalität (Video, Audio, Bild nativ)',
      'Gut bei Recherche mit echten Google-Quellen',
    ],
    weak: ['Außerhalb von Google-Tools weniger Mehrwert', 'UI-Workflow ist noch nicht so aufgeräumt wie ChatGPT/Claude'],
    useFor: 'Unternehmen, die bereits auf Google Workspace laufen.',
    pricing: 'Free / 22 € mtl. (Google One AI Premium)',
    access: 'gemini.google.com',
  },
  {
    id: 'perplexity', name: 'Perplexity', maker: 'Perplexity AI',
    logoBg: '#20808D', logoMark: 'P',
    category: 'chat', tier: 'essential',
    tags: ['Recherche', 'Web', 'Quellen'],
    url: 'perplexity.ai',
    oneLine: 'Die AI-Suchmaschine — gibt Antworten mit echten, klickbaren Quellen.',
    body: 'Wenn ich Fakten brauche, die ich zitieren muss — Wettbewerb, Marktdaten, aktuelle Entwicklungen — gehe ich zu Perplexity. Jede Antwort kommt mit Fußnoten zu echten URLs, die ich direkt prüfen kann.',
    example: '"Wie viele Betriebe in Hamburg im Handwerk, Stand 2025?" → Antwort mit IHK-Quelle direkt verlinkt.',
    strengths: [
      'Antworten mit verifizierbaren Quellen',
      'Immer auf aktuellem Stand (Web-Suche integriert)',
      'Pro-Mode durchsucht wissenschaftliche Paper',
      'Großartig für Marktrecherche und Fact-Checking',
    ],
    weak: ['Kein Tool für kreative Texterstellung', 'Kein Artefakt-Feature wie Claude/ChatGPT'],
    useFor: 'Recherche, Fact-Checking, Marktüberblick. Der Google-Ersatz für anspruchsvolle Fragen.',
    pricing: 'Free / 20 € mtl.',
    access: 'perplexity.ai',
  },
  {
    id: 'gamma', name: 'Gamma', maker: 'Gamma App',
    logoBg: '#8B5CF6', logoMark: 'G',
    category: 'work', tier: 'advanced',
    tags: ['Präsentation', 'Deck', 'Auto-Layout'],
    url: 'gamma.app',
    oneLine: 'Präsentationen aus Prompt — ersetzt das erste Stunde-Gefummel in PowerPoint.',
    body: 'Gamma baut in 30 Sekunden eine Roh-Präsentation aus einem Stichpunkt-Zettel oder Prompt. Nicht perfekt, aber als Startpunkt rettet es Ihnen oft eine ganze Stunde. Exportiert sauber nach PowerPoint.',
    example: '"10 Folien zu unserem Q4-Zahlen-Update für den Gesellschafterkreis" → bearbeitbares Deck in 30 Sek.',
    strengths: [
      'Rohes Deck in Sekunden — großartiger Start',
      'Automatisches Layout (keine PowerPoint-Fummelei)',
      'Export nach PPTX und PDF',
      'Auch für Docs und Webseiten nutzbar',
    ],
    weak: ['Eigenes Design-System lässt sich nur teilweise hinterlegen', 'Bei sehr individuellen Layouts stößt es schnell an Grenzen'],
    useFor: 'Wenn Sie regelmäßig Pitches, Berichte oder Update-Decks brauchen.',
    pricing: 'Free / 10 € mtl.',
    access: 'gamma.app',
  },
  {
    id: 'midjourney', name: 'Midjourney', maker: 'Midjourney Inc.',
    logoBg: '#0D0D0D', logoMark: 'M',
    category: 'media', tier: 'essential',
    tags: ['Bild', 'Art', 'Mood'],
    url: 'midjourney.com',
    oneLine: 'Für Bilder mit ästhetischem Anspruch — Moodboards, Ads, Header-Motive.',
    body: 'Wenn ich ein Bild brauche, das mehr ist als ein Stock-Foto — ein Mood, eine Atmosphäre, ein Stil — nutze ich Midjourney. Die Qualität ist unerreicht, aber die Lernkurve ist höher als bei DALL·E.',
    example: 'Hero-Image für eine Landing Page. Pitch-Deck-Titelfolie. Thumbnail für einen Blog-Artikel.',
    strengths: ['Höchste Bildqualität im Markt', 'Starker Stil-Transfer über Referenzbilder', 'Gute Kontrolle über Komposition und Farbe'],
    weak: ['Keine Integration in Workflows', 'Text in Bildern schwach', 'Lernkurve — Prompt-Sprache muss man üben'],
    useFor: 'Marketing, Design-Mockups, visuelle Inspiration. Nicht für Icons oder technische Diagramme.',
    pricing: 'Ab 10 € mtl.',
    access: 'midjourney.com',
  },
  {
    id: 'elevenlabs', name: 'ElevenLabs', maker: 'ElevenLabs',
    logoBg: '#0F1626', logoMark: '11',
    category: 'media', tier: 'essential',
    tags: ['Audio', 'Voice', 'TTS'],
    url: 'elevenlabs.io',
    oneLine: 'Text-to-Speech auf Studio-Niveau — mit deutscher Stimme, die nicht nach Roboter klingt.',
    body: 'Wenn Sie Audio-Content brauchen — Podcasts, Video-Voiceover, Anrufbeantworter-Texte — ElevenLabs liefert deutsche Stimmen, die man nicht mehr als AI erkennt. Stimm-Klonen funktioniert auch zuverlässig.',
    example: 'Produkt-Explainer-Video: Text schreiben → 30 Sekunden später ist die Vertonung fertig.',
    strengths: ['Beste deutsche AI-Stimmen', 'Voice-Cloning (mit Einwilligung)', 'API für Integration in eigene Tools', 'Studio-Qualität ohne Studio'],
    weak: ['Kein eigenes Sprach-Verständnis (nur Ausgabe)', 'Gute Stimmen kosten Guthaben — nicht trivial zu budgetieren'],
    useFor: 'Video, Podcast, Telefon-Ansagen. Überall wo Sie professionelles Audio brauchen, aber kein Studio haben.',
    pricing: 'Free / ab 5 € mtl.',
    access: 'elevenlabs.io',
  },
  {
    id: 'cursor', name: 'Cursor', maker: 'Anysphere',
    logoBg: '#111827', logoMark: 'C',
    category: 'build', tier: 'essential',
    tags: ['Code', 'IDE', 'Agent'],
    url: 'cursor.sh',
    oneLine: 'Der Code-Editor, der mitdenkt — meine Wahl für Eigenentwicklung.',
    body: 'Cursor ist ein vollwertiger Editor (VS-Code-Basis) mit AI direkt eingebaut. Schreibt mit Ihnen zusammen Code, führt ganze Refactorings durch, debuggt in Dialog. Wenn Sie oder Ihr Team selbst baut, ist der Produktivitätsgewinn real.',
    example: 'Python-Skript, das CSVs zusammenführt? In 5 Minuten ein lauffähiger Prototyp. Refactoring einer Altlast? Schritt-für-Schritt begleitet.',
    strengths: ['Verständnis ganzer Codebases, nicht nur Snippets', 'Agent-Mode — führt Task-Sequenzen aus', 'Funktioniert mit Claude, GPT-4, Gemini je nach Aufgabe', 'Kommt aus VS Code — bekannte UI'],
    weak: ['Nur sinnvoll, wenn Sie code-affin sind', 'Kann bei großen Änderungen zu übereifrig sein'],
    useFor: 'Entwicklerteams, technische Gründer, Automatisierer, die selbst Hand anlegen.',
    pricing: 'Free / 20 € mtl.',
    access: 'cursor.com',
  },
  {
    id: 'n8n', name: 'n8n', maker: 'n8n.io',
    logoBg: '#EA4B71', logoMark: 'n',
    category: 'build', tier: 'essential',
    tags: ['Automation', 'Workflow', 'Integration'],
    url: 'n8n.io',
    oneLine: 'Verbindet Ihre Tools miteinander — der Motor meiner Automatisierungs-Projekte.',
    body: 'n8n ist das Tool hinter den Kulissen bei fast jedem meiner Automatisierungs-Projekte. Verbindet Gmail, CRM, Buchhaltung, AI-APIs, Kalender — alles per Drag-and-Drop. Selbst hostbar (wichtig für DSGVO) und erweiterbar mit eigenem Code, wenn nötig.',
    example: 'Eingehende E-Mail → Claude extrahiert Kundendaten → CRM anlegen → Kalender-Termin → Bestätigung zurückschicken. Alles ohne manuelles Zutun.',
    strengths: ['400+ Integrationen fertig', 'Selbst hostbar — DSGVO-freundlich', 'Kombiniert klassische Automation mit AI-Schritten', 'Open-Source-Kern — keine Lock-in-Falle'],
    weak: ['Lernkurve — komplexe Flows brauchen Planung', 'Fehlerbehandlung will gelernt sein'],
    useFor: 'Immer, wenn Sie wiederkehrende Prozesse haben, die Zeit fressen. Mein Lieblings-Einstiegstool.',
    pricing: 'Self-host free / Cloud ab 20 € mtl.',
    access: 'n8n.io',
  },
];

/* ---------- Lightweight tools (one-liner only) ---------- */
function lite(id, name, maker, category, tier, tags, oneLine, url, logoBg, logoMark) {
  return { id, name, maker, category, tier, tags, oneLine, url, access: url, logoBg, logoMark };
}

const LITE = [
  // Chat / Assistenz
  lite('langdock',    'Langdock',    'Langdock',     'chat', 'essential', ['Team-AI', 'EU'],
       'Team-Plattform für AI im Unternehmen — DSGVO-konform, eigene Daten anbinden.', 'langdock.com', '#0E1F3A', 'L'),
  lite('openrouter',  'OpenRouter',  'OpenRouter',   'chat', 'advanced',  ['Models', 'API'],
       'Ein API-Zugang zu Dutzenden Modellen (Claude, GPT, Llama …) — flexibel und günstig abrechnen.', 'openrouter.ai', '#0F172A', 'OR'),
  lite('langchain',   'LangChain',   'LangChain',    'chat', 'advanced',  ['Framework', 'Dev'],
       'Framework für AI-Anwendungen — wenn Sie eigene Agenten und Pipelines bauen.', 'langchain.com', '#1E293B', 'LC'),
  lite('llamaindex',  'LlamaIndex',  'LlamaIndex',   'chat', 'advanced',  ['RAG', 'Dev'],
       'RAG-Framework — eigene Wissensdatenbanken an LLMs anbinden.', 'llamaindex.ai', '#111827', 'LI'),
  lite('dust',        'Dust',        'Dust',         'chat', 'advanced',  ['Team-AI', 'Agents'],
       'AI-Assistenten für Teams mit Anbindung an Notion, Slack, Drive.', 'dust.tt', '#7C3AED', 'D'),
  lite('flowise',     'Flowise',     'Flowise',      'chat', 'advanced',  ['No-Code', 'Agents'],
       'Drag-and-Drop-Builder für AI-Workflows — Open Source.', 'flowiseai.com', '#16A34A', 'F'),

  // Bild & Audio
  lite('dalle',       'DALL·E',      'OpenAI',       'media', 'essential', ['Bild'],
       'Bildgenerierung direkt in ChatGPT integriert — der einfachste Einstieg.', 'openai.com', '#10A37F', 'D'),
  lite('firefly',     'Adobe Firefly','Adobe',       'media', 'essential', ['Bild', 'Adobe'],
       'Bilder generieren mit kommerzieller Lizenz — nahtlos in Photoshop & Co.', 'firefly.adobe.com', '#FA0F00', 'Af'),
  lite('stability',   'Stability AI','Stability AI', 'media', 'advanced',  ['Bild', 'Open'],
       'Open-Source-Modelle (Stable Diffusion) — selbst hosten, voll kontrollierbar.', 'stability.ai', '#0F0F0F', 'S'),
  lite('replicate',   'Replicate',   'Replicate',    'media', 'advanced',  ['Models', 'API'],
       'Hunderte AI-Modelle per API — bezahlen pro Nutzung, kein Server-Setup.', 'replicate.com', '#000000', 'R'),
  lite('suno',        'Suno',        'Suno',         'media', 'advanced',  ['Musik', 'Audio'],
       'Komplette Songs aus Prompt — Musik, Gesang, Arrangement.', 'suno.ai', '#0EA5E9', 'S'),
  lite('playht',      'PlayHT',      'PlayHT',       'media', 'advanced',  ['Voice', 'TTS'],
       'Text-to-Speech-Alternative zu ElevenLabs — günstiger bei Volumen.', 'play.ht', '#FF4F4F', 'P'),
  lite('nanobanana',  'Nanobanana',  'Nanobanana',   'media', 'advanced',  ['Bild'],
       'Schnelle Bild-Iteration mit kurzen Prompts — gut für Social Content.', 'nanobanana.com', '#FACC15', 'Nb'),
  lite('fal',         'fal.ai',      'fal.ai',       'media', 'advanced',  ['Models', 'API'],
       'Schnelle Bild- und Video-Modelle per API — niedrige Latenz.', 'fal.ai', '#EC4899', 'fa'),
  lite('krea',        'Krea',        'Krea',         'media', 'advanced',  ['Bild', 'Realtime'],
       'Live-Bildgenerierung — was Sie zeichnen, wird sofort zum AI-Bild.', 'krea.ai', '#000000', 'K'),
  lite('magnific',    'Magnific',    'Magnific',     'media', 'advanced',  ['Upscale'],
       'Bilder hochskalieren mit AI — für Druck und Großformat.', 'magnific.ai', '#7C3AED', 'M'),
  lite('freepik',     'Freepik',     'Freepik',      'media', 'essential', ['Stock', 'Bild'],
       'Stock-Plattform mit AI-Tools — Bilder, Vektoren, jetzt auch Generatoren.', 'freepik.com', '#1273EB', 'Fp'),

  // Video
  lite('runway',      'Runway',      'Runway ML',    'video', 'essential', ['Video', 'Gen'],
       'Video-Generierung und -Bearbeitung — der Marktführer für AI-Video.', 'runwayml.com', '#000000', 'R'),
  lite('heygen',      'HeyGen',      'HeyGen',       'video', 'essential', ['Avatar', 'Video'],
       'AI-Avatare mit eigener Stimme — perfekt für Erklärvideos auf Skala.', 'heygen.com', '#7C3AED', 'H'),
  lite('capcut',      'CapCut',      'CapCut',       'video', 'essential', ['Schnitt', 'Mobile'],
       'Video-Schnitt mit AI-Features — kostenlos, Mobile und Desktop.', 'capcut.com', '#000000', 'Cc'),
  lite('kling',       'Kling',       'Kuaishou',     'video', 'advanced',  ['Video', 'Gen'],
       'Chinesischer Video-Generator — sehr realistische Bewegung und Lip-Sync.', 'klingai.com', '#0EA5E9', 'Kl'),
  lite('seedance',    'Seedance 2.0','ByteDance',    'video', 'advanced',  ['Video', 'Gen'],
       'ByteDance-Modell für AI-Video — dynamische Kamera-Moves.', 'seedance.ai', '#FF1744', 'Sd'),
  lite('pika',        'Pika Labs',   'Pika',         'video', 'advanced',  ['Video', 'Gen'],
       'Kurze AI-Videos aus Text und Bild — schnell und kreativ.', 'pika.art', '#FB7185', 'Pk'),
  lite('synthesia',   'Synthesia',   'Synthesia',    'video', 'advanced',  ['Avatar', 'B2B'],
       'Enterprise-Avatare für Schulungs- und Firmenvideos — DSGVO-tauglich.', 'synthesia.io', '#FF1744', 'Sy'),
  lite('descript',    'Descript',    'Descript',     'video', 'advanced',  ['Schnitt', 'Audio'],
       'Video & Podcast schneiden wie ein Word-Dokument — Text editieren = Audio editieren.', 'descript.com', '#7C3AED', 'De'),

  // Präsentation & Doku
  lite('notion',      'Notion',      'Notion Labs',  'work', 'essential', ['Docs', 'Wiki'],
       'Notizen, Wissens­datenbank und Doku — mit AI-Schreib­assistent eingebaut.', 'notion.so', '#000000', 'N'),
  lite('gdocs',       'Google Docs', 'Google',       'work', 'essential', ['Docs'],
       'Klassische Doc-Bearbeitung mit Gemini-Integration für AI-Hilfe.', 'docs.google.com', '#4285F4', 'Gd'),
  lite('canva',       'Canva',       'Canva',        'work', 'essential', ['Design', 'Magic'],
       'Grafiken und Decks für Nicht-Designer — AI-Magic-Features für Skalierung.', 'canva.com', '#00C4CC', 'Cv'),
  lite('tome',        'Tome',        'Tome',         'work', 'advanced',  ['Präsentation'],
       'AI-Präsentationen mit Storytelling-Ansatz — Alternative zu Gamma.', 'tome.app', '#000000', 'Tm'),
  lite('coda',        'Coda',        'Coda',         'work', 'advanced',  ['Docs', 'Database'],
       'Docs mit Tabellen-Intelligenz — wie Notion, aber stärker bei Daten.', 'coda.io', '#F46A54', 'Cd'),

  // Code & Automation
  lite('vscode',      'VS Code',     'Microsoft',    'build', 'essential', ['Editor'],
       'Der Standard-Code-Editor — Basis für viele AI-Plugins.', 'code.visualstudio.com', '#0E76A8', 'Vs'),
  lite('github',      'GitHub',      'GitHub',       'build', 'essential', ['Code', 'Hosting'],
       'Code-Hosting und Versionskontrolle — Heimat für jedes Software-Projekt.', 'github.com', '#181717', 'Gh'),
  lite('git',         'Git',         'Git Project',  'build', 'essential', ['Versioning'],
       'Versionskontrolle — die Grundlage moderner Software-Entwicklung.', 'git-scm.com', '#F05032', 'Gi'),

  // Daten & Backend
  lite('supabase',    'Supabase',    'Supabase',     'data', 'advanced',  ['Backend', 'DB'],
       'Postgres + Auth + Storage in einem Paket — Open-Source-Alternative zu Firebase.', 'supabase.com', '#3ECF8E', 'Sb'),
  lite('pinecone',    'Pinecone',    'Pinecone',     'data', 'advanced',  ['Vector DB'],
       'Vektordatenbank für RAG-Anwendungen — managed und schnell.', 'pinecone.io', '#000000', 'Pi'),
  lite('weaviate',    'Weaviate',    'Weaviate',     'data', 'advanced',  ['Vector DB'],
       'Open-Source-Vektordatenbank — selbst hostbar.', 'weaviate.io', '#22D3EE', 'Wv'),
  lite('modal',       'Modal',       'Modal Labs',   'data', 'advanced',  ['Compute'],
       'Serverless Python für AI-Workloads — GPU-Compute on-demand.', 'modal.com', '#7C3AED', 'Md'),
  lite('railway',     'Railway',     'Railway',      'data', 'advanced',  ['Hosting'],
       'Apps deployen ohne DevOps-Aufwand — Heroku-Alternative für Vibes.', 'railway.app', '#0B0D0E', 'Ry'),
  lite('vercel',      'Vercel',      'Vercel',       'data', 'advanced',  ['Hosting'],
       'Frontend-Hosting für moderne Web-Apps — null Setup, sofort live.', 'vercel.com', '#000000', 'Vc'),
  lite('sqlite',      'SQLite',      'SQLite',       'data', 'advanced',  ['Database'],
       'Eingebettete Datenbank — keine Server, eine Datei. Perfekt für Prototypen.', 'sqlite.org', '#003B57', 'Sq'),
  lite('cloudflare',  'Cloudflare',  'Cloudflare',   'data', 'advanced',  ['Edge', 'CDN'],
       'CDN, DNS, Edge-Compute — die Adern des modernen Webs.', 'cloudflare.com', '#F38020', 'Cf'),
  lite('apify',       'Apify',       'Apify',        'data', 'advanced',  ['Scraping'],
       'Web-Scraping als Service — strukturierte Daten aus jeder Website.', 'apify.com', '#FF9012', 'Ap'),
  lite('nocodb',      'NocoDB',      'NocoDB',       'data', 'advanced',  ['Airtable'],
       'Open-Source-Airtable-Alternative — selbst hostbar.', 'nocodb.com', '#1F4F8F', 'Nc'),
  lite('gcloud',      'Google Cloud','Google',       'data', 'advanced',  ['Cloud'],
       'Hyperscaler — wenn Sie Enterprise-Compute, BigQuery oder Vertex AI brauchen.', 'cloud.google.com', '#4285F4', 'Gc'),

  // Productivity / Work-OS
  lite('todoist',     'Todoist',     'Todoist',      'work-os', 'essential', ['Tasks'],
       'Aufgaben-Manager mit AI-Smart-Add — das Standardtool für persönliche To-Dos.', 'todoist.com', '#E44332', 'Td'),
  lite('asana',       'Asana',       'Asana',        'work-os', 'essential', ['Projekte'],
       'Team-Projektmanagement — die ältere Alternative zu Linear/ClickUp.', 'asana.com', '#F06A6A', 'As'),
  lite('airtable',    'Airtable',    'Airtable',     'work-os', 'advanced',  ['Database'],
       'Datenbank, die wie Excel aussieht — der Klassiker für No-Code-Anwendungen.', 'airtable.com', '#FCB400', 'At'),
  lite('gdrive',      'Google Drive','Google',       'work-os', 'essential', ['Storage'],
       'Cloud-Speicher für Workspace-User — und Anker für Gemini-Integrationen.', 'drive.google.com', '#4285F4', 'Dr'),
  lite('gsheets',     'Google Sheets','Google',      'work-os', 'essential', ['Spreadsheet'],
       'Tabellen mit Gemini-Hilfe — Formeln und Analysen in natürlicher Sprache.', 'sheets.google.com', '#0F9D58', 'Sh'),
  lite('miro',        'Miro',        'Miro',         'work-os', 'advanced',  ['Whiteboard'],
       'Online-Whiteboard mit AI-Cluster und -Summary — für verteilte Teams.', 'miro.com', '#FFD02F', 'Mr'),
  lite('ifttt',       'IFTTT',       'IFTTT',        'work-os', 'advanced',  ['Automation'],
       '"If This Then That" — leichte Automation für Privat und kleine Teams.', 'ifttt.com', '#000000', 'If'),

  // Communication
  lite('whatsapp',    'WhatsApp',    'Meta',         'work-os', 'essential', ['Chat'],
       'Standard-Messenger — über die Business-API für Kunden­dialog automatisierbar.', 'whatsapp.com', '#25D366', 'Wa'),
  lite('telegram',    'Telegram',    'Telegram',     'work-os', 'advanced',  ['Chat', 'Bots'],
       'Messenger mit starker Bot-API — schnell für Notifications und kleine Tools.', 'telegram.org', '#26A5E4', 'Tg'),
  lite('slack',       'Slack',       'Slack',        'work-os', 'essential', ['Team-Chat'],
       'Team-Kommunikation mit AI-Threads-Summary und Bot-Integrationen.', 'slack.com', '#4A154B', 'Sl'),
  lite('gmail',       'Gmail',       'Google',       'work-os', 'essential', ['E-Mail'],
       'Standard-Mail mit Gemini-Hilfe — Antwort­vorschläge und Zusammen­fassungen.', 'mail.google.com', '#EA4335', 'Gm'),

  // Design
  lite('figma',       'Figma',       'Figma',        'design', 'essential', ['UI', 'Design'],
       'Standard für UI- und Produktdesign — kollaborativ im Browser.', 'figma.com', '#F24E1E', 'Fi'),
  lite('framer',      'Framer',      'Framer',       'design', 'advanced',  ['Web', 'Design'],
       'Designs als echte Webseite veröffentlichen — Code-frei.', 'framer.com', '#0055FF', 'Fr'),
  lite('excalidraw',  'Excalidraw',  'Excalidraw',   'design', 'essential', ['Sketch'],
       'Hand­gezeichnete Diagramme im Browser — perfekt für schnelle Skizzen.', 'excalidraw.com', '#000000', 'Ex'),
  lite('dribbble',    'Dribbble',    'Dribbble',     'design', 'advanced',  ['Inspiration'],
       'Design-Inspiration und -Showcase — für Mood und Trends.', 'dribbble.com', '#EA4C89', 'Dr'),
  lite('designcom',   'design.com',  'design.com',   'design', 'advanced',  ['Logo'],
       'AI-Generator für Logos und Markenidentität — für schnelle Starts.', 'design.com', '#5B5BD6', 'Dc'),

  // Marketing / Reach
  lite('x',           'X',           'X Corp',       'reach', 'essential', ['Social'],
       'Plattform für AI-Diskurs und Reichweite — wo neue Tools zuerst auftauchen.', 'x.com', '#000000', 'X'),
  lite('youtube',     'YouTube',     'Google',       'reach', 'essential', ['Video'],
       'Video-Plattform Nr. 1 — größter SEO-Hebel für Long-Form-Inhalte.', 'youtube.com', '#FF0000', 'Yt'),
  lite('instagram',   'Instagram',   'Meta',         'reach', 'essential', ['Social', 'Bild'],
       'Bild- und Reels-Plattform — visueller Vertrieb und Brand-Building.', 'instagram.com', '#E4405F', 'Ig'),
  lite('tiktok',      'TikTok',      'ByteDance',    'reach', 'essential', ['Video', 'Reach'],
       'Kurz-Video-Plattform mit größter organischer Reichweite — auch B2B nutzbar.', 'tiktok.com', '#000000', 'Tt'),
];

const TOOLS = [...DETAILED, ...LITE];

/* ---------- Strategic core stack ---------- */
const CORE_STACK = [
  { id: 'claude',    role: 'Chat / Assistenz' },
  { id: 'chatgpt',   role: 'Chat (Allrounder)' },
  { id: 'langdock',  role: 'Team-AI' },
  { id: 'n8n',       role: 'Automation' },
  { id: 'supabase',  role: 'Backend' },
  { id: 'openrouter',role: 'Models' },
  { id: 'runway',    role: 'Video' },
  { id: 'kling',     role: 'Video (alternativ)' },
  { id: 'midjourney',role: 'Bild' },
];

window.TOOLS = TOOLS;
window.TOOL_CATEGORIES = TOOL_CATEGORIES;
window.TIERS = TIERS;
window.CORE_STACK = CORE_STACK;
